In [1]:
import geopandas as gpd
import re

In [ ]:
base_dir = "data/input/imm_startpop/"
start_pop_type = "StartPopulationChilderenR50.shp"
start_pop_type = "StartPopulationChilderenR50.shp"
start_pop_type = "StartPopulationChilderenR50.shp"

start_pop_dir = f"{base_dir}{start_pop_type}"

In [3]:
gdf_startpop = gpd.read_file(start_pop_dir)

In [ ]:
gdf_startpop.head(5)

,ID,Name,GGDREGION,DKTPVACCIN,SumOutJob,SumInJob,Difference,SumOutScho,SumInSchoo,F_OutComm,...,R18111,S18112,E18112,I18112,R18112,S19111,E19111,I19111,R19111,geometry
0,1,Aa0en0Hunze,Drenthe,97.2,9400,4200,-5200,1,1,36.80,...,0.0,269.10,0.0,0.0,0.0,4298.55,0.0,0.0,0.0,POINT (1585632.173 795714.596)
1,2,Aalburg,Fryslan,98.6,4600,3200,-1400,1,1,36.01,...,0.0,135.24,0.0,0.0,0.0,2149.86,0.0,0.0,0.0,POINT (1500318.421 636061.033)
2,3,Aalsmeer,Amsterdam,96.4,13900,11600,-2300,1,1,45.40,...,0.0,305.60,0.0,0.0,0.0,5153.01,0.0,0.0,0.0,POINT (1468943.336 688819.373)
3,4,Aalten,Noord- en Oost-Gelderland,98.2,11400,7200,-4200,1,1,42.09,...,0.0,276.08,0.0,0.0,0.0,4557.90,0.0,0.0,0.0,POINT (1598877.408 675265.265)
4,5,Achtkarspelen,Fryslan,98.6,10200,6000,-4200,1,1,36.29,...,0.0,297.10,0.0,0.0,0.0,4730.91,0.0,0.0,0.0,POINT (1541802.553 812393.98)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,392,Zundert,Fryslan,95.2,8900,5700,-3200,1,1,41.90,...,0.0,216.81,0.0,0.0,0.0,3574.86,0.0,0.0,0.0,POINT (1476481.993 601446.446)
392,393,Zutphen,Noord- en Oost-Gelderland,95.7,18700,20500,1800,1,1,39.59,...,0.0,489.24,0.0,0.0,0.0,7950.49,0.0,0.0,0.0,POINT (1571852.601 694444.604)
393,394,Zwartewaterland,Ijsselland,81.4,9100,7800,-1300,1,1,41.10,...,0.0,227.11,0.0,0.0,0.0,3725.99,0.0,0.0,0.0,POINT (1550140.52 743577.658)
394,395,Zwijndrecht,Zuid-Holland Zuid,99.1,18300,16200,-2100,1,1,41.02,...,0.0,457.86,0.0,0.0,0.0,7507.86,0.0,0.0,0.0,POINT (1467317.378 638824.418)
395,396,Zwolle,Ijsselland,98.2,58400,94300,35900,1,1,47.65,...,0.0,1205.49,0.0,0.0,0.0,20627.18,0.0,0.0,0.0,POINT (1555602.492 735076.352)

In [5]:
gdf_startpop[gdf_startpop["GGDREGION"]=="Utrecht"][["Name","TotPop"]]

                   Name  TotPop
12           Amersfoort  149662
20                Baarn   24277
57               Bunnik   14563
58           Bunschoten   20316
70              De0Bilt   42032
72       De0Ronde0Venen   42846
94               Eemnes    8795
163              Houten   48429
166         IJsselstein   34254
193             Leusden   28969
200               Lopik   13992
221           Montfoort   13621
228          Nieuwegein   60895
260           Oudewater    9872
273              Rhenen   19047
303               Soest   45508
313      Stichtse0Vecht   63491
331                 Urk   19225
332    Utrecht0gemeente  321916
337             Veendam   27914
344              Venray   43038
372  Wijk0bij0Duurstede   23035
376             Woerden   50346
378          Woudenberg   12321
385               Zeist   61420

In [6]:
pattern = re.compile(r"^[SIR]\d{5}$")
matched_pop_group_cols = [col for col in gdf_startpop.columns if pattern.match(col)]
list_cols_display = ["Name", "TotPop"] + matched_pop_group_cols

gdf_startpop = gdf_startpop[list_cols_display]

gdf_startpop["SumPop"] = gdf_startpop[matched_pop_group_cols].sum(axis=1)  

gdf_startpop["Check"] = gdf_startpop["TotPop"] == gdf_startpop["SumPop"]
gdf_startpop["diffSumPop"] = gdf_startpop["TotPop"] - gdf_startpop["SumPop"]

/var/folders/62/l81_5d_d7zs42vvzm3fgcr9m0000gn/T/ipykernel_5933/1708284292.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdf_startpop["SumPop"] = gdf_startpop[matched_pop_group_cols].sum(axis=1)
/var/folders/62/l81_5d_d7zs42vvzm3fgcr9m0000gn/T/ipykernel_5933/1708284292.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdf_startpop["Check"] = gdf_startpop["TotPop"] == gdf_startpop["SumPop"]
/var/folders/62/l81_5d_d7zs42vvzm3fgcr9m0000gn/T/ipykernel_5933/1708284292.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdf_startpop["diffSumPop"] = gdf_startpop["TotPop"] - gdf_startpop["SumPop"]

In [8]:
len(matched_pop_group_cols)

75

In [25]:
[col for col in gdf_startpop.columns if re.compile(r"^[S]\d{5}$").match(col)]

['S11112',
 'S12112',
 'S13112',
 'S14212',
 'S14112',
 'S15111',
 'S26311',
 'S26312',
 'S26111',
 'S26112',
 'S36322',
 'S36311',
 'S36312',
 'S36122',
 'S36111',
 'S36112',
 'S17311',
 'S17312',
 'S17111',
 'S17112',
 'S18311',
 'S18312',
 'S18111',
 'S18112',
 'S19111']

In [54]:
gdf_startpop["S19111"]/gdf_startpop["TotPop"]*100

0      16.829999
1      16.829967
2      16.830002
3      16.829998
4      16.829989
         ...
391    16.829999
392    16.829996
393    16.829983
394    16.829993
395    16.829996
Length: 396, dtype: float64

In [69]:
gdf_startpop[gdf_startpop["diffSumPop"].max() == gdf_startpop["diffSumPop"]]

,Name,TotPop,S11112,I11112,R11112,S12112,I12112,R12112,S13112,I13112,...,R18111,S18112,I18112,R18112,S19111,I19111,R19111,SumPop,Check,diffSumPop
14,Amsterdam,799278,3596.75,0.0,0.0,1798.375,0.0,1798.375,32290.83,0.0,...,0.0,8009.02,0.0,0.0,134518.49,0.0,0.0,762990.78,False,36287.22

In [66]:
gdf_startpop["diffSumPop"].max()

np.float64(36287.21999999997)

In [67]:
gdf_startpop["diffSumPop"].min()

np.float64(340.5)

In [65]:
gdf_startpop[gdf_startpop["diffSumPop"]<500]

,Name,TotPop,S11112,I11112,R11112,S12112,I12112,R12112,S13112,I13112,...,R18111,S18112,I18112,R18112,S19111,I19111,R19111,SumPop,Check,diffSumPop
11,Alphen0Chaam,9640,43.38,0.0,0.0,21.690,0.0,21.690,389.455,0.0,...,0.0,99.29,0.0,0.0,1622.41,0.0,0.0,9202.36,False,437.64
23,Bedum,10553,47.49,0.0,0.0,23.745,0.0,23.745,426.340,0.0,...,0.0,110.44,0.0,0.0,1776.07,0.0,0.0,10073.90,False,479.10
25,Beemster,8785,39.53,0.0,0.0,19.765,0.0,19.765,354.915,0.0,...,0.0,92.13,0.0,0.0,1478.52,0.0,0.0,8386.16,False,398.84
27,Bellingwedde,8985,40.43,0.0,0.0,20.215,0.0,20.215,362.995,0.0,...,0.0,97.94,0.0,0.0,1512.18,0.0,0.0,8577.08,False,407.92
28,Bergambacht,9938,44.72,0.0,0.0,22.360,0.0,22.360,401.495,0.0,...,0.0,105.08,0.0,0.0,1672.57,0.0,0.0,9486.82,False,451.18
41,Blaricum,9107,40.98,0.0,0.0,20.490,0.0,20.490,367.925,0.0,...,0.0,99.51,0.0,0.0,1532.71,0.0,0.0,8693.53,False,413.47
45,Boekel,10062,45.28,0.0,0.0,22.640,0.0,22.640,406.505,0.0,...,0.0,105.39,0.0,0.0,1693.43,0.0,0.0,9605.19,False,456.81
71,De0Marne,10336,46.51,0.0,0.0,23.255,0.0,23.255,417.575,0.0,...,0.0,112.15,0.0,0.0,1739.55,0.0,0.0,9866.74,False,469.26
94,Eemnes,8795,39.58,0.0,0.0,19.790,0.0,19.790,355.320,0.0,...,0.0,92.26,0.0,0.0,1480.20,0.0,0.0,8395.72,False,399.28
106,Ferwerderadiel,8856,39.85,0.0,0.0,19.925,0.0,19.925,357.780,0.0,...,0.0,93.69,0.0,0.0,1490.46,0.0,0.0,8453.93,False,402.07
108,Gaasterlan0Sleat,10196,45.88,0.0,0.0,22.940,0.0,22.940,411.920,0.0,...,0.0,107.76,0.0,0.0,1715.99,0.0,0.0,9733.10,False,462.90
151,het0Bildt,10646,47.91,0.0,0.0,23.955,0.0,23.955,430.100,0.0,...,0.0,112.93,0.0,0.0,1791.72,0.0,0.0,10162.70,False,483.30
174,Korendijk,10774,48.48,0.0,0.0,24.240,0.0,24.240,435.270,0.0,...,0.0,110.06,0.0,0.0,1813.26,0.0,0.0,10284.85,False,489.15
179,Landsmeer,10454,47.04,0.0,0.0,23.520,0.0,23.520,422.340,0.0,...,0.0,109.80,0.0,0.0,1759.41,0.0,0.0,9979.39,False,474.61
182,Laren0NH,10889,49.00,0.0,0.0,24.500,0.0,24.500,439.915,0.0,...,0.0,121.88,0.0,0.0,1832.62,0.0,0.0,10394.65,False,494.35
186,Leeuwarderadeel,10314,46.41,0.0,0.0,23.205,0.0,23.205,416.685,0.0,...,0.0,107.35,0.0,0.0,1735.85,0.0,0.0,9845.75,False,468.25
194,Lingewaal,11007,49.53,0.0,0.0,24.765,0.0,24.765,444.685,0.0,...,0.0,114.36,0.0,0.0,1852.48,0.0,0.0,10507.29,False,499.71
197,Littenseradiel,10948,49.27,0.0,0.0,24.635,0.0,24.635,442.300,0.0,...,0.0,114.89,0.0,0.0,1842.55,0.0,0.0,10450.97,False,497.03
201,Loppersum,10292,46.31,0.0,0.0,23.155,0.0,23.155,415.795,0.0,...,0.0,110.94,0.0,0.0,1732.14,0.0,0.0,9824.72,False,467.28
208,Marum,10382,46.72,0.0,0.0,23.360,0.0,23.360,419.435,0.0,...,0.0,108.23,0.0,0.0,1747.29,0.0,0.0,9910.66,False,471.34
217,Mill0en0Sint0Hubert,10906,49.08,0.0,0.0,24.540,0.0,24.540,440.600,0.0,...,0.0,111.77,0.0,0.0,1835.48,0.0,0.0,10410.89,False,495.11
222,Mook0en0Middelaar,7827,35.22,0.0,0.0,17.610,0.0,17.610,316.210,0.0,...,0.0,82.99,0.0,0.0,1317.28,0.0,0.0,7471.65,False,355.35
232,Noord0Beveland,7509,33.79,0.0,0.0,16.895,0.0,16.895,303.365,0.0,...,0.0,79.52,0.0,0.0,1263.76,0.0,0.0,7168.06,False,340.94
248,Onderbanken,7905,35.57,0.0,0.0,17.785,0.0,17.785,319.360,0.0,...,0.0,82.70,0.0,0.0,1330.41,0.0,0.0,7546.09,False,358.91
252,Oostzaan,9141,41.13,0.0,0.0,20.565,0.0,20.565,369.295,0.0,...,0.0,93.50,0.0,0.0,1538.43,0.0,0.0,8725.99,False,415.01
259,Ouderkerk,8147,36.66,0.0,0.0,18.330,0.0,18.330,329.140,0.0,...,0.0,85.18,0.0,0.0,1371.14,0.0,0.0,7777.12,False,369.88
260,Oudewater,9872,44.42,0.0,0.0,22.210,0.0,22.210,398.830,0.0,...,0.0,102.93,0.0,0.0,1661.46,0.0,0.0,9423.81,False,448.19
275,Rijnwaarden,10968,49.36,0.0,0.0,24.680,0.0,24.680,443.105,0.0,...,0.0,115.15,0.0,0.0,1845.91,0.0,0.0,10470.06,False,497.94
293,Simpelveld,10920,49.14,0.0,0.0,24.570,0.0,24.570,441.170,0.0,...,0.0,116.47,0.0,0.0,1837.84,0.0,0.0,10424.25,False,495.75
314,Strijen,8777,39.50,0.0,0.0,19.750,0.0,19.750,354.590,0.0,...,0.0,90.09,0.0,0.0,1477.17,0.0,0.0,8378.51,False,398.49
316,Ten0Boer,7500,33.75,0.0,0.0,16.875,0.0,16.875,303.000,0.0,...,0.0,78.76,0.0,0.0,1262.25,0.0,0.0,7159.50,False,340.50
334,Vaals,9771,43.97,0.0,0.0,21.985,0.0,21.985,394.750,0.0,...,0.0,111.96,0.0,0.0,1644.46,0.0,0.0,9327.39,False,443.61
349,Vlist,9730,43.79,0.0,0.0,21.895,0.0,21.895,393.090,0.0,...,0.0,101.75,0.0,0.0,1637.56,0.0,0.0,9288.28,False,441.72
388,Zoeterwoude,8122,36.55,0.0,0.0,18.275,0.0,18.275,328.130,0.0,...,0.0,82.92,0.0,0.0,1366.93,0.0,0.0,7753.26,False,368.74

In [68]:
gdf_startpop[["Name","TotPop", "SumPop", "Check", "diffSumPop"]]

                Name  TotPop     SumPop  Check  diffSumPop
0        Aa0en0Hunze   25541   24381.44  False     1159.56
1            Aalburg   12774   12194.05  False      579.95
2           Aalsmeer   30618   29227.93  False     1390.07
3             Aalten   27082   25852.47  False     1229.53
4      Achtkarspelen   28110   26833.81  False     1276.19
..               ...     ...        ...    ...         ...
391          Zundert   21241   20276.65  False      964.35
392          Zutphen   47240   45095.32  False     2144.68
393  Zwartewaterland   22139   21133.90  False     1005.10
394      Zwijndrecht   44610   42584.69  False     2025.31
395           Zwolle  122562  116997.70  False     5564.30

[396 rows x 5 columns]

In [ ]:
gdf_startpop[["Name","TotPop", "SumPop", "Check", "diffSumPop"]][gdf_startpop["Name"]=="Nieuwegein"]

           Name  TotPop    SumPop  Check  diffSumPop
228  Nieuwegein   60895  58130.38  False     2764.62

In [50]:
print("Tot population for Nieuwegein: ", gdf_startpop[gdf_startpop["Name"]=="Nieuwegein"][['TotPop']].values[0][0])

print("S19111 % for Nieuwegein: ", gdf_startpop[gdf_startpop["Name"]=="Nieuwegein"][['S19111']].values[0][0]/gdf_startpop[gdf_startpop["Name"]=="Nieuwegein"][['TotPop']].values[0][0]*100)
print("S19111 for Nieuwegein: ", gdf_startpop[gdf_startpop["Name"]=="Nieuwegein"][['S19111']].values[0][0])

print("65+ population for Nieuwegein according to CBS: ", 7688 + 4323)
print("65+ population % of total for Nieuwegein according to CBS: ", 12.6 + 2.9)

Tot population for Nieuwegein:  60895
S19111 % for Nieuwegein:  16.830002463256424
S19111 for Nieuwegein:  10248.63
65+ population for Nieuwegein according to CBS:  12011
65+ population % of total for Nieuwegein according to CBS:  15.5

In [40]:
gdf_startpop[gdf_startpop["Name"]=="Nieuwegein"]['S19111']/gdf_startpop[gdf_startpop["Name"]=="Nieuwegein"]['TotPop']

228    0.1683
dtype: float64