In [17]:
import pandas as pd

# Function to load and filter the CSV file
def filter_municipality(csv_file, municipality_name):
    # Load the CSV file with ';' as the delimiter
    df = pd.read_csv(csv_file, skiprows=[0,1], delimiter=';')

    # Strip column names of whitespace (useful for cleaner handling)
    df.columns = df.columns.str.strip()
    print(df.columns)
    
    # Filter rows based on the provided municipality name
    filtered_df = df[df['name'] == municipality_name]

    return filtered_df

# Example usage
csv_file = "imbit_model/data/output/OutputBasemodel.csv"  # Replace with your actual file path
municipality_name = " Amsterdam "  # Replace with the desired municipality

# filtered_df = filter_municipality(csv_file, municipality_name)

# filtered_df

In [12]:
# sum_components = (filtered_df['totalsusceptible'] +
#                       filtered_df['totalexposed'] +
#                       filtered_df['totalinfected'] +
#                       filtered_df['totalrecovered'])

# condition = filtered_df['totalpopulation'] == sum_components
# if not condition.all():
#     print("Warning: Some rows do not have totalpopulation equal to the sum of totalsusceptible, totalexposed, totalinfected, and totalrecovered.")
# else:
#     print("All rows satisfy the population condition.")

# print(sum_components)

In [20]:
pd.set_option('display.max_rows', None)
df = pd.read_csv(csv_file, skiprows=[0,1], delimiter=';')
df.columns = df.columns.str.strip()
print(df['totalnewinfected'].unique())

df[
    # (df['totalnewinfected'] > 0) &
    (df['name']== ' Amsterdam ')
    # (df['totalnewinfected']== 57) 
    # & (df["ticks"] < 53)
][["ticks", "name", "totalinfectedanimals", "totalspilloveranimalhumaninfections", "totalsusceptible", "totalexposed", "totalinfected", "totalrecovered", "totalnewinfected"]]

[0 1]

,ticks,name,totalinfectedanimals,totalspilloveranimalhumaninfections,totalsusceptible,totalexposed,totalinfected,totalrecovered,totalnewinfected
109,0,Amsterdam,0,0,190911,0,0,608287,0
508,1,Amsterdam,0,0,207487,0,0,591711,0
1051,2,Amsterdam,0,0,223610,0,0,575588,0
1474,3,Amsterdam,0,0,239291,0,0,559907,0
1828,4,Amsterdam,0,0,254542,0,0,544656,0
2318,5,Amsterdam,1,0,269375,0,0,529823,0
2640,6,Amsterdam,1,0,283802,0,0,515396,0
2958,7,Amsterdam,1,0,297834,0,0,501364,0
3356,8,Amsterdam,0,0,311481,0,0,487717,0
3914,9,Amsterdam,0,0,324755,0,0,474443,0
4110,10,Amsterdam,1,0,337665,0,0,461533,0
4442,11,Amsterdam,1,0,350221,0,0,448977,0
5020,12,Amsterdam,1,0,362433,0,0,436765,0
5527,13,Amsterdam,6,0,374310,0,0,424888,0
5777,14,Amsterdam,7,0,385862,0,0,413336,0
6104,15,Amsterdam,3,0,397098,0,0,402100,0
6532,16,Amsterdam,2,0,408026,0,0,391172,0
7093,17,Amsterdam,8,0,418654,0,0,380544,0
7297,18,Amsterdam,9,0,428991,0,0,370207,0
7882,19,Amsterdam,8,0,439045,0,0,360153,0
7971,20,Amsterdam,13,0,448824,0,0,350374,0
8670,21,Amsterdam,10,0,458334,0,0,340864,0
8825,22,Amsterdam,13,0,467584,0,0,331614,0
9477,23,Amsterdam,50,0,476581,0,0,322617,0
9662,24,Amsterdam,51,0,485331,0,0,313867,0
10219,25,Amsterdam,69,0,493841,0,0,305357,0
10522,26,Amsterdam,61,0,502119,0,0,297079,0
10740,27,Amsterdam,59,0,510169,0,0,289029,0
11349,28,Amsterdam,74,0,517999,0,0,281199,0
11538,29,Amsterdam,61,0,525615,0,0,273584,0
12168,30,Amsterdam,65,0,533021,0,0,266177,0
12631,31,Amsterdam,120,0,540225,0,0,258973,0
12956,32,Amsterdam,135,0,547232,0,0,251967,0
13099,33,Amsterdam,220,0,554046,0,0,245152,0
13509,34,Amsterdam,473,0,560674,0,0,238524,0
13986,35,Amsterdam,1058,1,567120,0,1,232078,1
14538,36,Amsterdam,1525,0,573390,0,1,225809,0
14792,37,Amsterdam,2533,0,579488,0,1,219711,0
15338,38,Amsterdam,2580,0,585418,0,1,213780,0
15593,39,Amsterdam,2580,0,591187,0,0,208012,0
16099,40,Amsterdam,4548,0,596797,0,0,202402,0
16376,41,Amsterdam,3984,0,602253,0,0,196945,0
16822,42,Amsterdam,3479,1,607560,0,1,191638,1
17229,43,Amsterdam,2903,0,612722,0,1,186477,0
17530,44,Amsterdam,4454,0,617742,0,1,181457,0
17895,45,Amsterdam,6237,0,622625,0,1,176574,0
18302,46,Amsterdam,5546,0,627374,0,1,171825,0
18873,47,Amsterdam,5851,0,631993,0,1,167207,0
19212,48,Amsterdam,7226,0,636485,0,0,162714,0
19708,49,Amsterdam,6479,1,640854,0,1,158345,1
19998,50,Amsterdam,16113,0,645104,0,1,154096,0
20352,51,Amsterdam,18369,0,649237,0,1,149963,0
20835,52,Amsterdam,17904,0,653257,0,1,145943,0
21040,53,Amsterdam,14460,0,657167,0,1,142034,0
21522,54,Amsterdam,21609,0,660969,0,1,138231,0
21884,55,Amsterdam,23286,0,664668,0,1,134533,0
22236,56,Amsterdam,29639,1,668265,0,1,130936,0
22656,57,Amsterdam,35976,0,671763,0,1,127437,0
23148,58,Amsterdam,40666,0,675166,0,1,124035,0
23673,59,Amsterdam,31084,0,678476,0,1,120725,0
24135,60,Amsterdam,27685,0,681694,0,1,117507,0
24318,61,Amsterdam,25700,0,684825,0,1,114376,0
24700,62,Amsterdam,27233,0,687870,0,1,111331,0
25301,63,Amsterdam,20251,1,690831,0,2,108370,1
25648,64,Amsterdam,16023,0,693712,0,1,105490,0
26100,65,Amsterdam,14355,0,696513,0,1,102689,0
26484,66,Amsterdam,12054,0,699238,0,1,99964,0
26760,67,Amsterdam,9928,0,701888,0,1,97314,0
27285,68,Amsterdam,11938,0,704465,0,1,94737,0
27387,69,Amsterdam,9934,0,706972,0,1,92230,0
27833,70,Amsterdam,11617,1,709410,0,2,89792,1
28419,71,Amsterdam,10616,0,711782,0,1,87421,0
28582,72,Amsterdam,12872,0,714088,0,1,85115,0
29186,73,Amsterdam,11056,0,716331,0,1,82872,0
29549,74,Amsterdam,8489,0,718513,0,1,80690,0
29827,75,Amsterdam,7278,0,720635,0,1,78568,0
30202,76,Amsterdam,7858,0,722699,0,1,76505,0
30684,77,Amsterdam,8868,1,724706,0,2,74497,1
31181,78,Amsterdam,10347,0,726658,0,1,72545,0
31459,79,Amsterdam,11279,0,728557,0,1,70647,0
31806,80,Amsterdam,11488,0,730404,0,1,68800,0
32194,81,Amsterdam,15552,0,732200,0,1,67004,0
32668,82,Amsterdam,14936,0,733947,0,1,65257,0
33052,83,Amsterdam,14073,0,735646,0,1,63558,0
33462,84,Amsterdam,14773,1,737299,0,2,61905,1
33671,85,Amsterdam,13360,0,738906,0,1,60298,0
34116,86,Amsterdam,12672,0,740469,0,1,58735,0
34663,87,Amsterdam,13589,0,741990,0,1,57215,0
34956,88,Amsterdam,14335,0,743469,0,1,55736,0
35305,89,Amsterdam,14334,0,744907,0,1,54298,0
35876,90,Amsterdam,13499,0,746306,0,1,52899,0
36174,91,Amsterdam,12427,1,747667,0,2,51539,1
36819,92,Amsterdam,12021,0,748990,0,1,50216,0
36953,93,Amsterdam,11153,0,750277,0,1,48929,0
37338,94,Amsterdam,9447,0,751529,0,1,47677,0
37744,95,Amsterdam,9563,0,752746,0,1,46460,0
38166,96,Amsterdam,7816,0,753930,0,1,45276,0
38797,97,Amsterdam,6817,0,755082,0,1,44124,0
38972,98,Amsterdam,5910,1,756202,0,2,43004,1
39404,99,Amsterdam,5205,0,757292,0,1,41915,0
39974,100,Amsterdam,4624,0,758351,0,1,40855,0
40322,101,Amsterdam,4268,0,759382,0,1,39825,0
40646,102,Amsterdam,3605,0,760384,0,1,38823,0
40993,103,Amsterdam,3298,0,761359,0,1,37848,0
41262,104,Amsterdam,2445,0,762308,0,1,36900,0
41874,105,Amsterdam,2060,1,763230,0,2,35978,1
42265,106,Amsterdam,1577,0,764127,0,1,35081,0
42706,107,Amsterdam,1498,0,764999,0,1,34209,0
42814,108,Amsterdam,1432,0,765848,0,1,33360,0
43167,109,Amsterdam,1486,0,766673,0,1,32535,0
43729,110,Amsterdam,1224,0,767476,0,1,31733,0
44249,111,Amsterdam,1110,0,768256,0,1,30952,0
44446,112,Amsterdam,1065,1,769016,0,2,30193,1
45071,113,Amsterdam,999,0,769754,0,1,29455,0
45437,114,Amsterdam,650,0,770472,0,1,28737,0
45669,115,Amsterdam,577,0,771171,0,1,28038,0
46128,116,Amsterdam,526,0,771850,0,1,27359,0
46334,117,Amsterdam,493,0,772511,0,1,26698,0
46926,118,Amsterdam,490,0,773154,0,1,26055,0
47170,119,Amsterdam,414,0,773779,0,1,25430,0
47640,120,Amsterdam,348,0,774387,0,0,24822,0
48192,121,Amsterdam,0,0,774978,0,0,24231,0
48606,122,Amsterdam,0,0,775554,0,0,23656,0
49001,123,Amsterdam,0,0,776113,0,0,23097,0
49318,124,Amsterdam,0,0,776657,0,0,22553,0
49776,125,Amsterdam,0,0,777186,0,0,22023,0
50199,126,Amsterdam,0,0,777701,0,0,21509,0
50428,127,Amsterdam,0,0,778202,0,0,21008,0
50856,128,Amsterdam,0,0,778688,0,0,20521,0
51175,129,Amsterdam,0,0,779162,0,0,20048,0
51717,130,Amsterdam,0,0,779623,0,0,19587,0
52118,131,Amsterdam,0,0,780070,0,0,19139,0
52591,132,Amsterdam,0,0,780506,0,0,18704,0
52804,133,Amsterdam,0,0,780930,0,0,18280,0
53238,134,Amsterdam,0,0,781342,0,0,17868,0
53825,135,Amsterdam,0,0,781743,0,0,17467,0
54037,136,Amsterdam,0,0,782133,0,0,17077,0
54626,137,Amsterdam,0,0,782512,0,0,16698,0
54656,138,Amsterdam,0,0,782881,0,0,16329,0
55363,139,Amsterdam,0,0,783239,0,0,15971,0
55800,140,Amsterdam,0,0,783588,0,0,15622,0
56231,141,Amsterdam,0,0,783928,0,0,15282,0
56497,142,Amsterdam,0,0,784258,0,0,14952,0
56658,143,Amsterdam,0,0,784579,0,0,14631,0
57087,144,Amsterdam,0,0,784891,0,0,14319,0
57724,145,Amsterdam,0,0,785194,0,0,14016,0
57967,146,Amsterdam,0,0,785490,0,0,13720,0
58249,147,Amsterdam,0,0,785777,0,0,13433,0
58703,148,Amsterdam,0,0,786056,0,0,13154,0
59149,149,Amsterdam,0,0,786328,0,0,12882,0
59489,150,Amsterdam,0,0,786592,0,0,12618,0
59939,151,Amsterdam,0,0,786849,0,0,12361,0
60311,152,Amsterdam,0,0,787099,0,0,12111,0
60589,153,Amsterdam,0,0,787342,0,0,11868,0
61186,154,Amsterdam,0,0,787579,0,0,11631,0
61416,155,Amsterdam,0,0,787809,0,0,11401,0
61878,156,Amsterdam,0,0,788032,0,0,11178,0
62237,157,Amsterdam,0,0,788250,0,0,10960,0
62688,158,Amsterdam,0,0,788461,0,0,10749,0
63169,159,Amsterdam,0,0,788667,0,0,10543,0
63648,160,Amsterdam,0,0,788867,0,0,10343,0
64144,161,Amsterdam,0,0,789062,0,0,10148,0
64404,162,Amsterdam,0,0,789251,0,0,9959,0
64906,163,Amsterdam,0,0,789436,0,0,9774,0
65306,164,Amsterdam,0,0,789615,0,0,9595,0
65393,165,Amsterdam,0,0,789789,0,0,9421,0
65858,166,Amsterdam,0,0,789958,0,0,9252,0
66505,167,Amsterdam,0,0,790123,0,0,9087,0
66582,168,Amsterdam,0,0,790283,0,0,8927,0
67217,169,Amsterdam,0,0,790439,0,0,8771,0
67400,170,Amsterdam,0,0,790591,0,0,8619,0
67737,171,Amsterdam,0,0,790738,0,0,8472,0
68159,172,Amsterdam,0,0,790882,0,0,8328,0
68635,173,Amsterdam,0,0,791021,0,0,8189,0
69203,174,Amsterdam,0,0,791157,0,0,8053,0

In [13]:
# Function to load and filter the CSV file
def filter_animal_infections(csv_file):
    # Load the CSV file with ';' as the delimiter
    df = pd.read_csv(csv_file, skiprows=[0,1], delimiter=';')

    # Strip column names of whitespace (useful for cleaner handling)
    df.columns = df.columns.str.strip()
    
    # Filter rows to show only cases we have animal infections
    filtered_df = df[
        (df['totalnewinfected'] > 0) 
    ]

    return filtered_df

In [18]:
pd.set_option('display.max_rows', None)
df = pd.read_csv(csv_file, skiprows=[0,1], delimiter=';')
df.columns = df.columns.str.strip()
# print(df['totalnewinfected'].unique())

df[
    # (df['totalnewinfected'] > 0) &
    (df['name']== ' Amsterdam ')
    # (df['totalnewinfected']== 57) 
    # & (df["ticks"] < 53)
][["ticks", "name", "totalinfectedanimals", "totalspilloveranimalhumaninfections", "totalsusceptible", "totalexposed", "totalinfected", "totalrecovered", "totalnewinfected"]]

,ticks,name,totalinfectedanimals,totalspilloveranimalhumaninfections,totalsusceptible,totalexposed,totalinfected,totalrecovered,totalnewinfected
375,0,Amsterdam,0,0,190911,0,0,608287,0
557,1,Amsterdam,0,0,207487,0,0,591711,0
872,2,Amsterdam,0,0,223610,0,0,575588,0
1471,3,Amsterdam,0,0,239291,0,0,559907,0
1603,4,Amsterdam,0,0,254542,0,0,544656,0
2081,5,Amsterdam,1,0,269375,0,0,529823,0
2535,6,Amsterdam,1,0,283802,0,0,515396,0
2935,7,Amsterdam,1,0,297834,0,0,501364,0
3228,8,Amsterdam,0,0,311481,0,0,487717,0
3934,9,Amsterdam,0,0,324755,0,0,474443,0
3987,10,Amsterdam,1,0,337665,0,0,461533,0
4726,11,Amsterdam,1,0,350221,0,0,448977,0
4895,12,Amsterdam,1,0,362433,0,0,436765,0
5273,13,Amsterdam,6,0,374310,0,0,424888,0
5694,14,Amsterdam,7,0,385862,0,0,413336,0
6036,15,Amsterdam,3,0,397098,0,0,402100,0
6631,16,Amsterdam,2,0,408026,0,0,391172,0
6813,17,Amsterdam,8,0,418654,0,0,380544,0
7326,18,Amsterdam,9,0,428991,0,0,370207,0
7579,19,Amsterdam,8,0,439045,0,0,360153,0
8009,20,Amsterdam,13,0,448824,0,0,350374,0
8625,21,Amsterdam,10,0,458334,0,0,340864,0
9071,22,Amsterdam,13,0,467584,0,0,331614,0
9230,23,Amsterdam,50,0,476581,0,0,322617,0
9802,24,Amsterdam,51,0,485331,0,0,313867,0
10156,25,Amsterdam,69,0,493841,0,0,305357,0
10535,26,Amsterdam,61,0,502119,0,0,297079,0
11021,27,Amsterdam,59,0,510169,0,0,289029,0
11171,28,Amsterdam,74,0,517999,0,0,281199,0
11667,29,Amsterdam,61,0,525615,0,0,273584,0
12210,30,Amsterdam,65,0,533021,0,0,266177,0
12493,31,Amsterdam,120,0,540225,0,0,258973,0
12855,32,Amsterdam,135,0,547232,0,0,251967,0
13068,33,Amsterdam,220,0,554046,0,0,245152,0
13535,34,Amsterdam,473,0,560674,0,0,238524,0
14137,35,Amsterdam,1058,1,567120,0,1,232078,1
14631,36,Amsterdam,1525,0,573388,2,1,225809,0
14977,37,Amsterdam,2533,0,579484,3,1,219711,0
15197,38,Amsterdam,2580,0,585413,5,1,213780,0
15649,39,Amsterdam,2580,0,591179,7,2,208012,1
15840,40,Amsterdam,4548,0,596785,9,3,202402,1
16452,41,Amsterdam,3984,0,602236,14,4,196946,1
16639,42,Amsterdam,3479,1,607534,20,6,191640,2
17230,43,Amsterdam,2903,0,612681,31,9,186479,3
17428,44,Amsterdam,4454,0,617681,46,12,181460,3
18115,45,Amsterdam,6237,0,622534,68,18,176579,6
18557,46,Amsterdam,5546,0,627239,102,26,171833,8
18807,47,Amsterdam,5851,0,631791,152,39,167219,13
19207,48,Amsterdam,7226,0,636182,228,58,162732,19
19542,49,Amsterdam,6479,1,640399,343,87,158372,29
20094,50,Amsterdam,16113,0,644414,521,130,154137,43
20379,51,Amsterdam,18369,0,648192,791,195,150024,65
20667,52,Amsterdam,17904,0,651669,1203,294,146035,99
21336,53,Amsterdam,14460,0,654748,1836,446,142172,152
21673,54,Amsterdam,21609,0,657276,2809,677,138439,231
22128,55,Amsterdam,23286,0,659016,4304,1033,134848,356
22213,56,Amsterdam,29639,1,659607,6602,1579,131415,546
22677,57,Amsterdam,35976,0,658493,10127,2416,128166,837
23311,58,Amsterdam,40666,0,654854,15501,3701,125146,1285
23653,59,Amsterdam,31084,0,647489,23623,5668,122423,1967
23932,60,Amsterdam,27685,0,634729,35711,8660,120102,2992
24332,61,Amsterdam,25700,0,614422,53268,13169,118344,4509
24753,62,Amsterdam,27233,0,594177,67788,19852,117385,6683
24955,63,Amsterdam,20251,1,564433,89361,27842,117566,7990
25498,64,Amsterdam,16023,0,526092,115942,38095,119074,10253
26121,65,Amsterdam,14355,0,501078,124805,51070,122250,12975
26468,66,Amsterdam,12054,0,469831,138512,63359,127501,12289
26805,67,Amsterdam,9928,0,434913,153749,75884,134657,12525
27323,68,Amsterdam,11938,0,397812,168826,88862,143704,12978
27353,69,Amsterdam,9934,0,359517,182830,102189,154666,13327
28026,70,Amsterdam,11617,1,320843,195182,115630,167549,13441
28493,71,Amsterdam,10616,0,282613,205382,128889,182320,13259
28742,72,Amsterdam,12872,0,245738,212933,141638,198896,12749
28954,73,Amsterdam,11056,0,211156,217386,153520,217142,11882
29428,74,Amsterdam,8489,0,179706,218465,164165,236869,10645
29723,75,Amsterdam,7278,0,152001,216158,173215,257831,9050
30161,76,Amsterdam,7858,0,128357,210749,180372,279726,7157
30746,77,Amsterdam,8868,1,88430,223125,185436,302215,5064
31026,78,Amsterdam,10347,0,63526,219030,191717,324931,6281
31300,79,Amsterdam,11279,0,47493,207370,196269,348073,4552
31995,80,Amsterdam,11488,0,45767,183978,198119,371340,1850
32246,81,Amsterdam,15552,0,44461,164704,195763,394278,0
32527,82,Amsterdam,14936,0,43885,148539,190586,416195,0
33053,83,Amsterdam,14073,0,35786,143192,183578,436649,0

In [ ]:
pd.set_option('display.max_rows', None)
df = pd.read_csv(csv_file, skiprows=[0,1], delimiter=';')
df.columns = df.columns.str.strip()
# print(df['totalnewinfected'].unique())

df[
    # (df['totalnewinfected'] > 0) &
    (df['name']== ' Amsterdam ')
    # (df['totalnewinfected']== 57) 
    & (df["ticks"] < 53)
][["ticks", "name", "totalinfectedanimals", "totalspilloveranimalhumaninfections", "totalsusceptible", "totalexposed", "totalinfected", "totalrecovered", "totalnewinfected"]]

In [7]:

pd.set_option('display.max_rows', None)
df = pd.read_csv("imbit_model/data/output/OutputBasemodel_copy.csv" , skiprows=[0,1], delimiter=';')
df.columns = df.columns.str.strip()
# print(df['totalnewinfected'].unique())

df[
    # (df['totalnewinfected'] > 0) &
    (df['name']== ' Amsterdam ')
    # (df['totalnewinfected']== 57) 
    & (df["ticks"] < 53)
][["ticks", "name", "totalinfectedanimals", "totalspilloveranimalhumaninfections", "totalsusceptible", "totalexposed", "totalinfected", "totalrecovered", "totalnewinfected"]]

,ticks,name,totalinfectedanimals,totalspilloveranimalhumaninfections,totalsusceptible,totalexposed,totalinfected,totalrecovered,totalnewinfected
234,0,Amsterdam,0,0,190911,0,0,608287,0
534,1,Amsterdam,0,0,207487,0,0,591711,0
967,2,Amsterdam,0,0,223610,0,0,575588,0
1368,3,Amsterdam,0,0,239291,0,0,559907,0
1953,4,Amsterdam,0,0,254542,0,0,544656,0
2337,5,Amsterdam,0,0,269375,0,0,529823,0
2614,6,Amsterdam,0,0,283802,0,0,515396,0
2855,7,Amsterdam,1,0,297834,0,0,501364,0
3411,8,Amsterdam,1,0,311481,0,0,487717,0
3769,9,Amsterdam,1,0,324755,0,0,474443,0
4301,10,Amsterdam,1,0,337665,0,0,461533,0
4736,11,Amsterdam,1,0,350221,0,0,448977,0
4816,12,Amsterdam,1,0,362433,0,0,436765,0
5431,13,Amsterdam,1,0,374310,0,0,424888,0
5834,14,Amsterdam,8,0,385862,0,0,413336,0
6322,15,Amsterdam,8,0,397098,0,0,402100,0
6477,16,Amsterdam,8,0,408026,0,0,391172,0
7124,17,Amsterdam,8,0,418654,0,0,380544,0
7155,18,Amsterdam,8,0,428991,0,0,370207,0
7839,19,Amsterdam,8,0,439045,0,0,360153,0
8070,20,Amsterdam,8,0,448824,0,0,350374,0
8707,21,Amsterdam,18,0,458334,0,0,340864,0
8950,22,Amsterdam,18,0,467584,0,0,331614,0
9378,23,Amsterdam,18,0,476581,0,0,322617,0
9644,24,Amsterdam,18,0,485331,0,0,313867,0
9923,25,Amsterdam,18,0,493841,0,0,305357,0
10538,26,Amsterdam,18,0,502119,0,0,297079,0
10845,27,Amsterdam,18,0,510169,0,0,289029,0
11256,28,Amsterdam,92,0,517999,0,0,281199,0
11725,29,Amsterdam,92,0,525615,0,0,273584,0
12171,30,Amsterdam,92,0,533021,0,0,266177,0
12458,31,Amsterdam,92,0,540225,0,0,258973,0
12746,32,Amsterdam,92,0,547232,0,0,251967,0
13109,33,Amsterdam,92,0,554046,0,0,245152,0
13593,34,Amsterdam,92,0,560674,0,0,238524,0
14009,35,Amsterdam,1150,1,567120,0,1,232078,1
14327,36,Amsterdam,1150,0,573387,3,1,225809,0
14929,37,Amsterdam,1150,0,579482,5,1,219711,0
15248,38,Amsterdam,1150,0,585410,7,2,213780,1
15751,39,Amsterdam,1150,0,591173,11,3,208012,1
15992,40,Amsterdam,1150,0,596776,16,4,202402,1
16382,41,Amsterdam,1150,0,602222,25,6,196947,2
16679,42,Amsterdam,4629,1,607512,37,10,191640,4
17138,43,Amsterdam,4629,0,612646,59,15,186480,5
17463,44,Amsterdam,4629,0,617626,89,22,181462,7
17844,45,Amsterdam,4629,0,622448,135,33,176583,11
18224,46,Amsterdam,4629,0,627104,206,50,171840,17
18693,47,Amsterdam,4629,0,631580,315,76,167229,26
19307,48,Amsterdam,4629,0,635853,482,116,162749,40
19485,49,Amsterdam,11108,1,639885,740,178,158398,62
19937,50,Amsterdam,11108,0,643613,1140,272,154176,94
20407,51,Amsterdam,11108,0,646941,1757,416,150086,144
20598,52,Amsterdam,11108,0,649718,2711,640,146132,224

In [9]:
pd.set_option('display.max_rows', None)
df = pd.read_csv(csv_file, skiprows=[0,1], delimiter=';')
df.columns = df.columns.str.strip()
print(df['totalnewinfected'].unique())

[  0   1   2   3   4   5   7  10  15  23  12  36  56  16  19  85 131  26
 203  33 315  42]

In [17]:
df = df[df["name"] == " Amsterdam "]

sum_components = (df['totalsusceptible'] +
                      df['totalexposed'] +
                      df['totalinfected'] +
                      df['totalrecovered'])

condition = df['totalpopulation'] == sum_components
if not condition.all():
    print("Warning: Some rows do not have totalpopulation equal to the sum of totalsusceptible, totalexposed, totalinfected, and totalrecovered.")
else:
    print("All rows satisfy the population condition.")

print(sum_components)

Warning: Some rows do not have totalpopulation equal to the sum of totalsusceptible, totalexposed, totalinfected, and totalrecovered.
26       806328
706      806328
914      806329
1406     806328
1805     806328
2076     806328
2731     806328
3142     806329
3174     806329
3617     806328
4272     806328
4717     806329
4951     806328
5335     806328
5547     806328
6093     806329
6548     806329
6875     806329
7167     806329
7649     806329
8083     806328
8511     806329
8718     806329
9109     806328
9733     806329
10056    806329
10608    806329
10752    806329
11268    806328
11532    806329
12056    806328
12295    806328
13061    806329
13152    806329
13704    806329
14238    806330
14439    806330
14656    806329
15140    806331
15769    806329
15876    806330
16400    806330
16941    806331
17224    806330
17788    806331
18209    806332
18607    806331
18734    806330
19325    806330
19432    806332
20046    806332
20381    806331
20782    806332
21198    806332
dtype: int64

In [15]:
df['totalpopulation']

0         73379
1         21842
2         32358
3         23647
4         21963
5         29358
6         10548
7         17908
8         12920
9         21704
10        32266
11        33720
12        42408
13       144074
14        28891
15        33181
16        54228
17        35439
18        22795
19        47789
20        36115
21       123636
22        43826
23        19469
24        76453
25        24307
26       806329
27        32924
28        32747
29       167846
30        46054
31        30606
32       158705
33        45587
34         7976
35        25793
36        47946
37        24286
38       119517
39        18358
40        11003
41        19303
42        28165
43        15571
44        13686
45        22847
46        60113
47        28894
48        19397
49        27927
50        23136
51        43681
52        22884
53        14116
54        26000
55         8194
56        27663
57        16420
58         8874
59        85613
60       220359
61        11480
62        18563
63        20660
64        14427
65        18410
66        26353
67        37942
68        24962
69        43417
70        17469
71        46849
72        25323
73        22755
74        86780
75        35529
76        43632
77        83377
78        55950
79        55219
80        17473
81        15358
82       197136
83        39096
84        22796
85        26641
86        24230
87        57191
88        43709
89        64051
90        11105
91       110796
92        22591
93        22395
94        24605
95       150972
96        73234
97        67801
98        16537
99        26260
100       18742
101       25941
102       37548
103       27322
104       34556
105       61432
106       25657
107        8855
108       21052
109       23359
110       32484
111       13742
112       57004
113       25770
114       15880
115       73554
116       43226
117       26974
118       25892
119       35144
120       26068
121       17244
122       55363
123       25547
124       25441
125       22710
126       19845
127       24184
128        9222
129       20495
130       11643
131       26286
132       15762
133      124176
134       17419
135       80182
136       39463
137       61970
138       28363
139       18080
140       32674
141       42648
142       10430
143       41042
144       12782
145       67715
146       43626
147       49015
148       14573
149       16228
150       26171
151      103596
152       18351
153       41139
154        9067
155       21620
156       10989
157      151155
158       66609
159       44847
160       11066
161       10385
162       21183
163      621782
164       13693
165       26554
166       25606
167       81668
168       29491
169       50898
170       33108
171       57453
172       22573
173       21430
174      122910
175       45167
176       12845
177       16282
178       47619
179       16965
180       32367
181       20510
182       21961
183       14572
184        9861
185       27137
186       23287
187       23973
188       36060
189       13659
190       12332
191       10027
192       10742
193       46677
194       32851
195       25889
196       18810
197       23609
198       17879
199       29113
200       32269
201       36807
202       94862
203       14030
204       54163
205      154441
206       46617
207       12431
208       10152
209       10648
210       28637
211      101047
212       12041
213       23429
214       12730
215       45007
216       73012
217        9726
218       26865
219       42176
220       27762
221       12606
222       99454
223       23468
224       10870
225       47795
226       16465
227       25825
228       34274
229       32015
230       16513
231       26474
232       21450
233       30856
234      160039
235       33017
236       77840
237       24439
238       14256
239       22099
240       30042
241       15543
242       30888
243       41367
244      510363
245       37767
246       25779
247       85129
248       15881
249       25743
250       27322
251       46943
252       53360
253       56915
254       37744
255       41813
256       35386
257       16601
258      196929
259       18085
260       26980
261       40424
262       13809
263       19808
264       11865
265       45913
266       12508
267       34707
268       11320
269       40712
270      109360
271       12875
272       24878
273       20904
274       19677
275       24538
276       15632
277       31303
278       24018
279        8220
280        7897
281       18364
282       29221
283       71536
284       15333
285       16875
286       28477
287       66876
288       15219
289       36738
290       24495
291       18792
292       30707
293       14595
294       24767
295       30136
296        7567
297       95337
298       21436
299       19787
300       18478
301       41311
302       27194
303       31850
304       37298
305       12161
306       23935
307       15331
308       11971
309      120852
310       34344
311       33607
312       30165
313        9960
314       22977
315       38250
316       48066
317       34833
318      150997
319       25271
320       14693
321       10406
322       12889
323       19264
324       21359
325       89813
326        9190
327       22053
328       63589
329       51374
330       11875
331       19818
332       45731
333        9817
334       10288
335       29449
336       19534
337       39113
338       29342
339       24101
340       12944
341       40133
342       14015
343       32693
344       48686
345       12481
346       71531
347        7577
348       71992
349       16277
350      210361
351       11018
352       19179
353       76894
354       10475
355       47662
356       18574
357       22336
358      179710
359       22468
360       48523
361       15998
362       13176
363       13849
364       13066
365       63238
366        8864
367       29225
368       96802
369       36950
370       16743
371       16933
372       23238
373       25442
374       28289
375       27814
376       18867
377       46224
378       50789
379       25898
380      324723
381       42122
382      150943
383       48853
384       12130
385       99976
386       36087
387       39431
388       11046
389        8936
390       44482
391       29226
392       13367
393       89541
394       19218
395       13394
396       34274
397       39113
398       26641
399        9817
400       30042
401      220359
402        7567
403       11875
404       61432
405       25441
406       22795
407       35439
408       19264
409       18810
410       22710
411       55219
412        8855
413       39431
414       40424
415        7577
416       66609
417       11320
418       42122
419       54228
420       19534
421       13686
422       29449
423       21450
424        8874
425       23287
426       47619
427      324723
428      210361
429       46054
430       33108
431       22336
432       25889
433       26000
434       71531
435       18792
436       64051
437       10870
438       46943
439       27194
440      154441
441        9190
442       16282
443       21620
444       34556
445       94862
446       15880
447       10989
448       26286
449       18867
450       28637
451       23468
452       18358
453       16228
454      124176
455       15998
456       89541
457       19818
458       13693
459       32269
460       18364
461       12730
462       36087
463       41367
464       25547
465       36060
466       26974
467      167846
468       46677
469       43626
470       51374
471       41311
472       10548
473       12875
474       27322
475       11865
476       16465
477       25442
478       40712
479       25743
480       21430
481       13742
482      196929
483       45167
484       46617
485       37548
486       37942
487      150943
488       23429
489       23359
490       29221
491       14693
492       18085
493       14572
494       47946
495       16601
496       48686
497       14116
498       22755
499       19808
500       15358
501       41139
502       30856
503       12332
504       43709
505       29358
506       23136
507       28891
508       32266
509       73379
510       23935
511       13394
512       18742
513       13849
514       18410
515       13659
516       45007
517       57191
518      109360
519       43681
520       21183
521       26980
522       11480
523       29225
524       15219
525       67715
526       13176
527      119517
528       42648
529        9726
530       16933
531       18478
532       41813
533      122910
534      144074
535       19303
536       17879
537       35144
538       29491
539        8936
540       12041
541       32367
542       20904
543       22099
544       12944
545       96802
546       30606
547       33607
548       86780
549       24184
550       43226
551       11046
552       11971
553       32015
554       48853
555       41042
556       95337
557       48066
558       14030
559       20510
560       17473
561       24962
562       26865
563       26554
564       19179
565       40133
566        7897
567       57453
568       10152
569      197136
570      151155
571       16965
572       21963
573       53360
574       12130
575       16743
576       22796
577       18351
578       50789
579       21961
580       12508
581       32674
582       17469
583       27663
584       55363
585       34707
586       14573
587       25825
588       33181
589       15632
590       21359
591       32851
592       31303
593       30165
594       11066
595       89813
596       35529
597       47789
598       10430
599       22573
600       24439
601       47662
602       15571
603       28894
604       20660
605       21052
606      120852
607       23238
608       30707
609       19218
610       28165
611       12920
612        8864
613       71536
614       42176
615        9960
616       27322
617       33720
618       73554
619       10742
620       73234
621       16513
622       22053
623       12481
624       11018
625       23973
626       16875
627       19469
628        9222
629       25779
630       32924
631       17244
632       22977
633       25898
634       55950
635       33017
636       99454
637       45587
638       66876
639       27137
640       12431
641      179710
642       34344
643       45731
644       25770
645       32358
646       57004
647       43417
648       19397
649       29226
650       32693
651       85613
652       85129
653       25606
654       44482
655       81668
656       17908
657       30888
658       17419
659       45913
660       26068
661       25271
662        8194
663       18080
664       22884
665       12606
666       18574
667       12889
668       14256
669       13367
670       24101
671       15881
672       11643
673       18563
674       11003
675       48523
676       43632
677       37298
678       16277
679       28477
680       76453
681       22395
682       56915
683       20495
684       44847
685       80182
686       38250
687       22847
688       26171
689        8220
690       15331
691       50898
692       10406
693      160039
694       37767
695       36807
696       22591
697       42408
698        9067
699       28289
700       24018
701       21842
702       12845
703       76894
704       12782
705       13066
706      806329
707       29342
708       24767
709       29113
710       25941
711       47795
712       10648
713      110796
714       14595
715       24307
716       63238
717       28363
718       21436
719       60113
720       14427
721       36115
722       16420
723       61970
724      101047
725       32747
726       71992
727       83377
728       10027
729       15762
730       54163
731       11105
732       24538
733       24230
734       26474
735      103596
736       19845
737       43826
738       24495
739       30136
740      150972
741       67801
742       39463
743      123636
744       23647
745       27814
746       73012
747        7976
748       15543
749      621782
750       36950
751       19677
752       36738
753      150997
754       13809
755       35386
756       37744
757       32484
758       10288
759        9861
760       16537
761       77840
762       39096
763       46849
764       22468
765       12161
766       24878
767       26353
768       24286
769       14015
770      510363
771       24605
772       26260
773       25892
774       15333
775      158705
776       63589
777       27927
778       46224
779       19787
780       34833
781       31850
782       25323
783       27762
784       10385
785       49015
786       21704
787       10475
788       25657
789       25793
790       99976
791       23609
792       21052
793       19787
794       16277
795       47619
796       24605
797        9222
798       48523
799       18574
800       28894
801        8936
802       26554
803       38250
804       11018
805       12875
806       17879
807       36807
808       18085
809       10548
810       24878
811       64051
812      150972
813       48066
814       27762
815      122910
816       17244
817       36738
818        7567
819       19677
820       35144
821       37767
822       40133
823       22099
824       33017
825      110796
826       34344
827       28637
828       24538
829       12944
830        7577
831       41813
832       17469
833        7897
834       32266
835       16228
836       39113
837       16965
838        8220
839       12508
840       26260
841       26865
842       45731
843       21430
844       67801
845       10027
846       57191
847       31850
848       36087
849       11865
850       18364
851       73012
852       45007
853       36950
854       18351
855       19534
856       57453
857      144074
858       25779
859       24101
860       27814
861       85129
862      120852
863       47795
864       26474
865       50789
866       29221
867       17908
868       11003
869       12161
870       23136
871       43632
872       25793
873       11480
874       46054
875       39431
876       23935
877       10475
878       22977
879       22847
880       15998
881       23238
882      101047
883       15880
884       49015
885       40424
886       30606
887      154441
888       10742
889       13367
890       85613
891       25889
892       39463
893       48686
894       26068
895       76453
896       14573
897      210361
898       23647
899       12606
900       19264
901       13066
902       56915
903       25606
904       42408
905       27322
906       11643
907       39096
908       83377
909       16282
910       34833
911       11875
912       29226
913       14595
914      806329
915        8864
916       25441
917       54163
918       17419
919       35529
920       21704
921       89541
922        8855
923       89813
924       23973
925       13394
926       14572
927      158705
928       21450
929       22710
930       12332
931       18410
932       61432
933       18792
934      510363
935       43826
936       25323
937       46849
938       53360
939       24962
940       26980
941       29358
942       60113
943       35386
944       16513
945       42122
946       16933
947       32693
948       22053
949       22796
950       10406
951       10989
952       24230
953       96802
954       20495
955       44482
956       27137
957       40712
958       22591
959       14116
960       21842
961       17473
962       13176
963       25941
964       21620
965       12920
966       35439
967       13693
968       27322
969       26641
970       21183
971      197136
972       19845
973       41367
974       23359
975       12730
976       10870
977       28363
978      124176
979       73379
980       19218
981      196929
982       12481
983       22395
984       13686
985       47789
986       50898
987      324723
988       16743
989       51374
990       19179
991       24439
992       29491
993       63589
994       67715
995       66609
996        9817
997        7976
998       77840
999       43226
1000     109360
1001      22884
1002      15762
1003      73554
1004      30136
1005      18478
1006      46943
1007      21963
1008      26974
1009      55219
1010      18742
1011      21961
1012      15219
1013      21436
1014     123636
1015      10430
1016      36060
1017      22573
1018      12130
1019      18810
1020      29342
1021      46224
1022      31303
1023      29113
1024      13742
1025      42648
1026      18080
1027      32674
1028      25770
1029      16465
1030      43681
1031      30888
1032      30856
1033      13659
1034      57004
1035      29449
1036      15331
1037      13849
1038      14427
1039      14256
1040     167846
1041      42176
1042      95337
1043      15333
1044      94862
1045      24495
1046      41311
1047      32358
1048      45167
1049      22468
1050      20660
1051      19469
1052      73234
1053      25898
1054      25892
1055      16601
1056     621782
1057      16875
1058      30707
1059      25442
1060      99454
1061      55950
1062      29225
1063      26286
1064      24307
1065      71992
1066      61970
1067      30165
1068     179710
1069      32269
1070      32924
1071      26353
1072      36115
1073      32851
1074       9861
1075       9960
1076      15543
1077      41042
1078      26000
1079      33108
1080      48853
1081      47946
1082      24286
1083      27927
1084      34707
1085      28891
1086      12845
1087      16537
1088      34274
1089      27663
1090      22755
1091      63238
1092      46677
1093      11066
1094      15358
1095      28165
1096      46617
1097      32367
1098      21359
1099      25657
1100      23429
1101     150997
1102      80182
1103     151155
1104      43417
1105      22795
1106      37298
1107      71536
1108      20510
1109      71531
1110      37942
1111       9190
1112      33720
1113      76894
1114      10648
1115      24767
1116      19818
1117     119517
1118      14015
1119      99976
1120      32015
1121      26171
1122      25547
1123      23468
1124      81668
1125      11105
1126      12782
1127      37548
1128      11320
1129      25743
1130      16420
1131       9067
1132     103596
1133       8194
1134       9726
1135      18867
1136      25825
1137      14030
1138      41139
1139      28477
1140      22336
1141       8874
1142      37744
1143      43709
1144      18358
1145      34556
1146      12889
1147      43626
1148      10385
1149      30042
1150      66876
1151      23287
1152      11046
1153      24018
1154      32747
1155      20904
1156      15632
1157      15881
1158     220359
1159      33181
1160      12431
1161      25271
1162      28289
1163      24184
1164      13809
1165     160039
1166      55363
1167      47662
1168      86780
1169      12041
1170      32484
1171      19303
1172      15571
1173      19808
1174      54228
1175      19397
1176      45587
1177      44847
1178      10288
1179      18563
1180      10152
1181     150943
1182      11971
1183      14693
1184      33607
1185      23609
1186      27194
1187      45913
1188      13659
1189     109360
1190      26171
1191      37767
1192      18792
1193      61432
1194      10870
1195      42648
1196      11066
1197      40712
1198      13693
1199      30136
1200      19818
1201      15998
1202      25441
1203      21183
1204     122910
1205      53360
1206      13686
1207      23973
1208      18410
1209      64051
1210      27194
1211      46224
1212      67801
1213      39463
1214      19179
1215      19264
1216      18810
1217     120852
1218      60113
1219      28363
1220      23287
1221      40424
1222      19534
1223      29358
1224      34274
1225      36115
1226      55950
1227      32693
1228      20495
1229      12889
1230      20904
1231      45731
1232       8874
1233      27137
1234      47619
1235      45587
1236      21436
1237       9861
1238      18085
1239     220359
1240      63589
1241      11018
1242      15762
1243      31303
1244      10288
1245      37942
1246      14256
1247      17469
1248      32367
1249      14427